version: '3.8'

x-common-variables:
  &common
  HELLOWORLD_SERVICE_PORT: "3001"
  HELLOWORLD_SERVICE_ADDR: "helloworld"
  POSTGRES_DB: aniapp
  POSTGRES_USER: user
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

services:
  customer-api-gateway:
    build:
      context: ./customer-api-gateway
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      <<: *common
      NODE_ENV: development
      PORT: "3000"
      DEBUG: nodejs-docker-express:*
    networks:
      - aniapp

  customer-service:
    container_name: customer-service
    build:
      context: ./customer-service
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
    networks:
      - aniapp

  pet-service:
    container_name: pet-service
    build:
      context: ./pet-service
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3002:3002"
    env_file:
      - 'pet.env'
    networks:
      - aniapp
    depends_on:
      - pet-db

  pet-db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      <<: *common
    networks:
      - aniapp
  veterinary-service:
    container_name: veterinary-service
    build:
      context: ./veterinary-service
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
    networks:
      - aniapp

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      <<: *common
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniapp

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: pgadmin4
  #  restart: always
  #  ports:
  #    - "5050:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: tuncel.ahmet.berke@gmail.com
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  volumes:
  #    - pgadmin-data:/var/lib/pgadmin
  #  networks:
  #    - aniapp

volumes:
  pgadmin-data:

networks:
  aniapp:
    driver: bridge