version: '3.8'

x-common-variables:
  &common
  HELLOWORLD_SERVICE_PORT: "3001"
  HELLOWORLD_SERVICE_ADDR: "helloworld"

services:
  customer-api-gateway:
    build: 
      context: ./customer-api-gateway
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      <<: *common
      NODE_ENV: development
      PORT: "3000"
      DEBUG: nodejs-docker-express:*
    networks:
      - aniapp

  helloworld:
    container_name: helloworld
    build: 
      context: ./helloworld-service
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      - HELLOWORLD_SERVICE_PORT=3001
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
    networks:
      - aniapp

  db:
    image: postgres
    container_name: local_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tuncel.ahmet.berke@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  aniapp:
    driver: bridge